1. ‘봄’ , ‘여름’, ‘가을’, ‘겨울’에 대한 representation 값을 각각 (1,2), (-1,3), (2,-2), (2,1)이라고 했을 때, 아래의 순서에 따른 positional encoding 값을 더한 각 단어의 representation 값을 구하시오. Transformer의 positional encoding을 사용하시오.
a. [ ‘여름’, ‘가을’, ‘겨울’, ‘봄’]

In [ ]:
import math
import matplotlib.pyplot as plt

n = 4
dim = 2

def get_angles(pos, i, dim):
  angles = 1/math.pow(10000,(2*(i//2))/dim)
  return pos * angles

def get_positional_encoding(pos,i,dim):
  if i%2==0:
    return math.sin(get_angles(pos,i,dim))
  return math.cos(get_angles(pos,i,dim))

result = [[0] * dim for _ in range(n)]

for i in range(n):
  for j in range(dim):
    result[i][j] = get_positional_encoding(i,j,dim)

print(result)

In [ ]:
import numpy as np
representation = np.array([[-1,3],[2,-2],[2,1],[1,2]])
positional_embedding = np.array(result)

representation + positional_embedding

array([[-1.        ,  4.        ],
       [ 2.84147098, -1.45969769],
       [ 2.90929743,  0.58385316],
       [ 1.14112001,  1.0100075 ]])

3. Transformer 모델에서 vector size = 3 이다.
[I , am , a , student] 를 Q, K , V 로 한 결과가 아래와 같을 때 QI에 대한 attention 출력값을 구하시오.
- QI = [2, 4, 6]
- KI = [2, 4, 6], Kam=[1, 2, 4], Ka=[0, 1, 2], Kstudent=[1, 1, 1]
- VI = [0.5, 0.3, 0.2], Vam=[0.6, 0.1, 0.3], Va=[0.1, 0.7, 0.2], Vstudent=[0.4, 0.5, 0.1]

In [ ]:
import torch
import torch.nn
import math

Q = torch.FloatTensor([2,4,6])
Kt = torch.FloatTensor([[2,1,0,1],[4,2,1,1],[6,4,2,1]])
V = torch.FloatTensor([[0.5,0.3,0.2],[0.6,0.1,0.3],[0.1,0.7,0.2],[0.4,0.5,0.1]])
embedding_d = 3
QKt = torch.matmul(Q,Kt)
ad_QKt = QKt/math.sqrt(embedding_d)

QKt

tensor([56., 34., 16., 12.])

In [ ]:
ad_QKt

tensor([32.3316, 19.6299,  9.2376,  6.9282])

In [ ]:
expQKt = torch.exp(ad_QKt)
sum_expQKt = torch.sum(expQKt)
softmax = expQKt/sum_expQKt

softmax

tensor([1.0000e+00, 3.0459e-06, 9.3411e-11, 9.2776e-12])

In [ ]:
torch.matmul(softmax,V)

tensor([0.5000, 0.3000, 0.2000])